### PR TITLE
Fix 14.04 support

### LINKED ISSUE #696: Build not working on 14.04
It looks like an issue with the gcc package for firmware.  I created the `justin/ci-test` branch to track down the issue - it's the same as master except with an extra line appended to `ubuntu-setup` to trigger a rebuild of the CI image.  Here's the error:

~~~{.sh}
WARNING: The following packages cannot be authenticated!
  gcc-arm-none-eabi
E: There are problems and -y was used without --force-yes
[ERR] Your setup command FAILED. Exiting...
/home/ubuntu/robocup-software/external/DoCIF/util/maketest.sh: line 90: cd: /home/developer/project: No such file or directory

./external/DoCIF/commands/buildbaseimage.sh returned exit code 1

Action failed: ./external/DoCIF/commands/buildbaseimage.sh
~~~

### PR DESCRIPTION
**Pull request by jgkamat**
Closes #696

@ryanstrat could you check out the jay/14.04 branch on your computer and rerun ubuntu setup, and see if that works? 

If you've prevously run ubuntu-setup (on an older commit) could you run `sudo apt-get remove gcc-arm-none-eabi` before trying again?

I _think_ this works on a fresh install of 14.04, according to docker. I'm not going to change the CI because I'm too lazy, and this is way less hacky.

It dosen't seem to be working on the firmware build due to missing `strtok_r`? @justbuchanan do you know anything about this?

`#include <string.h>` dosen't fix it.

```
/home/developer/project/firmware/robot2015/src-ctrl/modules/ControllerTaskThread.cpp: In function 'void Task_Controller(const void*)':
/home/developer/project/firmware/robot2015/src-ctrl/modules/ControllerTaskThread.cpp:150:90: note: #pragma message: TODO: remeasure the duty cycle and rad / s relationship of the motor
/home/developer/project/firmware/robot2015/src-ctrl/modules/commands/commands.cpp: In function 'void execute_line(char*)':
/home/developer/project/firmware/robot2015/src-ctrl/modules/commands/commands.cpp:1125:51: error: 'strtok_r' was not declared in this scope
     char* cmds = strtok_r(rawCommand, ";", &endCmd);
                                                   ^
firmware/robot2015/src-ctrl/CMakeFiles/robot2015_elf.dir/build.make:158: recipe for target 'firmware/robot2015/src-ctrl/CMakeFiles/robot2015_elf.dir/modules/commands/commands.cpp.o' failed
make[4]: *** [firmware/robot2015/src-ctrl/CMakeFiles/robot2015_elf.dir/modules/commands/commands.cpp.o] Error 1
make[4]: *** Waiting for unfinished jobs....
/home/developer/project/firmware/robot2015/src-ctrl/main.cpp: In function 'int main()':
/home/developer/project/firmware/robot2015/src-ctrl/main.cpp:138:10: warning: unused variable 'kickerReady' [-Wunused-variable]
     bool kickerReady = kickerBoard.flash(true, true);
          ^
CMakeFiles/Makefile2:1124: recipe for target 'firmware/robot2015/src-ctrl/CMakeFiles/robot2015_elf.dir/all' failed
make[3]: *** [firmware/robot2015/src-ctrl/CMakeFiles/robot2015_elf.dir/all] Error 2
CMakeFiles/Makefile2:1067: recipe for target 'firmware/robot2015/src-ctrl/CMakeFiles/robot2015.dir/rule' failed
make[2]: *** [firmware/robot2015/src-ctrl/CMakeFiles/robot2015.dir/rule] Error 2
Makefile:415: recipe for target 'robot2015' failed
make[1]: *** [robot2015] Error 2
makefile:104: recipe for target 'robot2015' failed
make: *** [robot2015] Error 2
```

### CODE REVIEW

**Comment by jgkamat** [comment]
The firmware build error is related to updating the arm compiler to version 5+ maybe. See: https://launchpad.net/~team-gcc-arm-embedded/+archive/ubuntu/ppa

Maybe someone should file a bug?

**Comment by ryanstrat** [comment]
If keeping up with this will be annoying, could we add build targets in CMake that just don't compile the firmware?

Right now it's not possible to only compile soccer.

**Comment by jgkamat** [comment]
This branch should be able to compile everything except for `make robot2015`. The firmware tests still work somehow, which is confusing...

If you want to do both, you can download [this deb file](https://launchpad.net/~team-gcc-arm-embedded/+archive/ubuntu/ppa/+files/gcc-arm-embedded_4.9-2015q2-1~utopic1_amd64.deb) (after removing the ones installed by apt), and that should work for everything.

**Comment by justbuchanan** [comment]
I've seen the `strtok_r` error before on Arch and I just fixed it locally by editing `string.h`... definitely not a good solution, but it worked as a quick fix.  @ryanstrat shouldn't need firmware for his work, so I wouldn't worry about 14.04 firmware too much.

@ryanstrat, when you run `make`, it shouldn't be building anything firmware related - it just builds soccer, simulator, log_viewer, etc.  Do firmware-related build items cause problems for you when you just try to build soccer?

**Comment by jgkamat** [comment]
@justbuchanan yes, they do seem to have some impact on the build for just plain soccer. I *think* its just compiling the dpendencies for the mbed libs, but I'm not sure.
See: https://circle-artifacts.com/gh/RoboJackets/robocup-software/2204/artifacts/0/tmp/circle-artifacts.XWN3nrY/compile.txt

**Comment by justbuchanan** [comment]
That's strange... it does seem to be compiling the mbed libraries.  That should only happen if one of the firmware targets is being built - it should never happen when you run `make` or `make all`.  I tried it on my computer and it doesn't do anything firmware-related when I run `make`.

I'll look into it - it may have something to do with the CI having an older version of `cmake` or `ninja`.

**Comment by jgkamat** [comment]
Yah, this was on 14.04, so that could be very likely. Its probably not worth diagnosing because we're going to move to 16.04 anyway next year, and we'll have the newer versions.

**Comment by ryanstrat** [comment]
It works enough for me to compile soccer!

Thanks!

**Comment by jgkamat** [comment]
:+1: 
I think this should be merged (but if people run ubuntu-setup it would break their setups, unless they clean out the arm utils they have currently...)
What do you think @justbuchanan?

**Comment by justbuchanan** [comment]
Sounds good to me, go for it.  Maybe just post a quick note in the gitter to let people know how to fix things if they have trouble with firmware compilation.
